apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.name | lower | replace "." "-"  | replace "_" "-" }}
  labels:
    app: {{ .Values.microservice.name | lower | replace "." "-"  | replace "_" "-" }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.microservice.name | lower | replace "." "-"  | replace "_" "-" }}
