apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'spring-petclinic-preprod'
spec:
  destination:
      server: 'https://kubernetes.default.svc'
      namespace: preprod
  source:
      repoURL: 'git@github.com:Anumrati/cicd.git'
      path: helm_charts/microservice/java
      targetRevision: HEAD
      helm:
        valueFiles:
          - values/preprod/spring-petclinic.yaml
  project: 'default'
  syncPolicy:
    automated:
      prune: false
      selfHeal: false