apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/jenkins/jenkins_home
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
